<a href="https://colab.research.google.com/github/bibhushi15/Bibhushi_Python_Assignment/blob/main/Project_python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [ ]:
df = pd.read_csv("UPPER.csv")

In [ ]:
raw_df = df.copy()

In [ ]:
df.head()

,published_date,open,high,low,close,per_change,traded_quantity,traded_amount,status
0,2019-03-19,242.0,245.0,241.0,242.0,0.00,19638.0,4771501.0,0
1,2019-03-21,242.0,245.0,238.0,240.0,-0.83,38970.0,9365431.0,-1
2,2019-03-24,240.0,242.0,235.0,239.0,-0.42,41392.0,9872309.0,-1
3,2019-03-25,238.0,241.0,236.0,240.0,0.42,35260.0,8436025.0,1
4,2019-03-26,237.0,241.0,237.0,241.0,0.42,31029.0,7417514.0,1

In [ ]:
df.shape

(1723, 9)

In [ ]:
df.columns

Index(['published_date', 'open', 'high', 'low', 'close', 'per_change',
       'traded_quantity', 'traded_amount', 'status'],
      dtype='object')

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1723 entries, 0 to 1722
Data columns (total 9 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   published_date   1723 non-null   object
 1   open             1723 non-null   float64
 2   high             1723 non-null   float64
 3   low              1723 non-null   float64
 4   close            1723 non-null   float64
 5   per_change       1723 non-null   float64
 6   traded_quantity  1723 non-null   float64
 7   traded_amount    1723 non-null   float64
 8   status           1723 non-null   int64
dtypes: float64(7), int64(1), object(1)
memory usage: 121.3+ KB

In [ ]:
df.describe()

,open,high,low,close,per_change,traded_quantity,traded_amount,status
count,1723.000000,1723.000000,1723.000000,1723.000000,1723.000000,1.723000e+03,1.723000e+03,1723.000000
mean,345.760917,352.314098,338.526872,344.122594,0.045177,1.434080e+05,5.092943e+07,-0.236796
std,190.076968,194.822431,184.327837,188.360681,2.515611,2.282419e+05,8.133203e+07,0.947332
min,152.500000,154.900000,152.100000,153.100000,-10.000000,3.000000e+01,6.470000e+03,-1.000000
25%,203.000000,206.000000,200.000000,202.080000,-1.200000,3.798850e+04,9.829031e+06,-1.000000
50%,240.000000,244.000000,235.500000,239.000000,-0.320000,7.802600e+04,2.209905e+07,-1.000000
75%,471.000000,480.000000,461.300000,470.000000,0.750000,1.557335e+05,5.236802e+07,1.000000
max,930.000000,962.500000,893.000000,908.000000,10.000000,2.768765e+06,8.958935e+08,1.000000

In [ ]:
df.isnull().sum()

published_date     0
open               0
high               0
low                0
close              0
per_change         0
traded_quantity    0
traded_amount      0
status             0
dtype: int64

In [ ]:
df.duplicated().sum()

np.int64(2)