<a href="https://colab.research.google.com/github/bibhushi15/Bibhushi_Python_Assignment/blob/main/Project_python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

*Importing necessary Libraries*

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [ ]:
df = pd.read_csv("UPPER.csv")

*Preserving original dataset*

In [ ]:
raw_df = df.copy()

In [ ]:
df.head()

,published_date,open,high,low,close,per_change,traded_quantity,traded_amount,status,year,month,day_name,daily_range,price_change,status_label
0,2019-03-19,242.0,245.0,241.0,242.0,0.00,19638,4771501.0,0,2019,3,Tuesday,4.0,0.0,No Change
1,2019-03-21,242.0,245.0,238.0,240.0,-0.83,38970,9365431.0,-1,2019,3,Thursday,7.0,-2.0,Loss
2,2019-03-24,240.0,242.0,235.0,239.0,-0.42,41392,9872309.0,-1,2019,3,Sunday,7.0,-1.0,Loss
3,2019-03-25,238.0,241.0,236.0,240.0,0.42,35260,8436025.0,1,2019,3,Monday,5.0,2.0,Gain
4,2019-03-26,237.0,241.0,237.0,241.0,0.42,31029,7417514.0,1,2019,3,Tuesday,4.0,4.0,Gain

# Basic Pre-processing Steps

In [ ]:
df.shape

(1721, 15)

In [ ]:
df.columns

Index(['published_date', 'open', 'high', 'low', 'close', 'per_change',
       'traded_quantity', 'traded_amount', 'status', 'year', 'month',
       'day_name', 'daily_range', 'price_change', 'status_label'],
      dtype='object')

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1721 entries, 0 to 1720
Data columns (total 15 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   published_date   1721 non-null   object
 1   open             1721 non-null   float64
 2   high             1721 non-null   float64
 3   low              1721 non-null   float64
 4   close            1721 non-null   float64
 5   per_change       1721 non-null   float64
 6   traded_quantity  1721 non-null   int64
 7   traded_amount    1721 non-null   float64
 8   status           1721 non-null   int64
 9   year             1721 non-null   int64
 10  month            1721 non-null   int64
 11  day_name         1721 non-null   object
 12  daily_range      1721 non-null   float64
 13  price_change     1721 non-null   float64
 14  status_label     1721 non-null   object
dtypes: float64(8), int64(4), object(3)
memory usage: 201.8+ KB

In [ ]:
df.describe()

,open,high,low,close,per_change,traded_quantity,traded_amount,status,year,month,daily_range,price_change
count,1721.000000,1721.000000,1721.000000,1721.000000,1721.000000,1.721000e+03,1.721000e+03,1721.000000,1721.000000,1721.000000,1721.000000,1721.000000
mean,345.936235,352.496915,338.698024,344.297809,0.044654,1.435560e+05,5.098503e+07,-0.235909,2022.524695,6.506682,13.798890,-1.638425
std,190.117779,194.861757,184.366506,188.399941,2.517025,2.283332e+05,8.136293e+07,0.947525,2.195291,3.372441,13.659759,12.138399
min,152.500000,154.900000,152.100000,153.100000,-10.000000,3.000000e+01,6.470000e+03,-1.000000,2019.000000,1.000000,1.000000,-69.000000
25%,203.000000,206.000000,200.000000,202.300000,-1.200000,3.805100e+04,9.872309e+06,-1.000000,2021.000000,4.000000,4.900000,-5.600000
50%,240.000000,244.000000,236.000000,239.000000,-0.330000,7.805000e+04,2.210681e+07,-1.000000,2023.000000,7.000000,8.900000,-1.000000
75%,472.000000,480.000000,461.600000,470.000000,0.750000,1.558230e+05,5.237619e+07,1.000000,2024.000000,9.000000,18.000000,2.000000
max,930.000000,962.500000,893.000000,908.000000,10.000000,2.768765e+06,8.958935e+08,1.000000,2026.000000,12.000000,112.000000,77.000000

In [ ]:
df.isnull().sum()

published_date     0
open               0
high               0
low                0
close              0
per_change         0
traded_quantity    0
traded_amount      0
status             0
year               0
month              0
day_name           0
daily_range        0
price_change       0
status_label       0
dtype: int64

In [ ]:
df.duplicated().sum()

np.int64(0)

In [ ]:
df[df.duplicated(keep=False)]

Empty DataFrame
Columns: [published_date, open, high, low, close, per_change, traded_quantity, traded_amount, status, year, month, day_name, daily_range, price_change, status_label]
Index: []

In [ ]:
df[df["close"] <= 0]

Empty DataFrame
Columns: [published_date, open, high, low, close, per_change, traded_quantity, traded_amount, status, year, month, day_name, daily_range, price_change, status_label]
Index: []

# Cleaning Process

Removing duplicates

In [ ]:
df = df.drop_duplicates().reset_index(drop=True)

print(f"Duplicates remaining: {df.duplicated().sum()}")
print(f"Total rows after removing duplicates: {df.shape[0]}")

Duplicates remaining: 0
Total rows after removing duplicates: 1721

Fixing the data-types

In [ ]:
# converting the date features into pandas date-time
df["published_date"] = pd.to_datetime(df["published_date"])

# shares sold are always in whole number
df["traded_quantity"] = df["traded_quantity"].astype(int)

Transforming the data

In [ ]:
# sorting by the date
df = df.sort_values(by="published_date").reset_index(drop=True)

In [ ]:
# extracting the year, month, and day from the pandas date-time
df["year"] = df["published_date"].dt.year
df["month"] = df["published_date"].dt.month
df["day_name"] = df["published_date"].dt.day_name()

*open and high are very important for NEPSE analysis to note the profit and loss in overall*

In [ ]:
df["price_change"] = (df["close"] - df["open"]).round(2)
df["daily_range"] = (df["high"] - df["low"]).round(2)

*Mapping the status for readibility*

In [ ]:
status_map = {1: "Gain", -1: "Loss", 0: "No Change"}
df["status_label"] = df["status"].map(status_map)

In [ ]:
# rounding off the traded amount
df["traded_amount"] = df["traded_amount"].round(2)

*Another important feature in trading analysis is, we see the price difference between yesterday's closing price and today's opening price*

In [ ]:
# getting yesterday's price with shift method
df['prev_close'] = df['close'].shift(1)

# calculating opening gap
df['opening_gap'] = (df['open'] - df['prev_close']).round(2)

In [ ]:
df.head(10)

,published_date,open,high,low,close,per_change,traded_quantity,traded_amount,status,year,month,day_name,daily_range,price_change,status_label,prev_close,opening_gap
0,2019-03-19,242.0,245.0,241.0,242.0,0.00,19638,4771501.0,0,2019,3,Tuesday,4.0,0.0,No Change,NaN,NaN
1,2019-03-21,242.0,245.0,238.0,240.0,-0.83,38970,9365431.0,-1,2019,3,Thursday,7.0,-2.0,Loss,242.0,0.0
2,2019-03-24,240.0,242.0,235.0,239.0,-0.42,41392,9872309.0,-1,2019,3,Sunday,7.0,-1.0,Loss,240.0,0.0
3,2019-03-25,238.0,241.0,236.0,240.0,0.42,35260,8436025.0,1,2019,3,Monday,5.0,2.0,Gain,239.0,-1.0
4,2019-03-26,237.0,241.0,237.0,241.0,0.42,31029,7417514.0,1,2019,3,Tuesday,4.0,4.0,Gain,240.0,-3.0
5,2019-03-27,237.0,241.0,236.0,240.0,-0.41,27337,6529071.0,-1,2019,3,Wednesday,5.0,3.0,Loss,241.0,-4.0
6,2019-03-28,239.0,241.0,238.0,240.0,0.00,24176,5779898.0,0,2019,3,Thursday,3.0,1.0,No Change,240.0,-1.0
7,2019-03-31,240.0,241.0,237.0,239.0,-0.42,38545,9214296.0,-1,2019,3,Sunday,4.0,-1.0,Loss,240.0,0.0
8,2019-04-01,239.0,239.0,236.0,238.0,-0.42,35591,8455362.0,-1,2019,4,Monday,3.0,-1.0,Loss,239.0,0.0
9,2019-04-02,237.0,240.0,237.0,237.0,-0.42,30721,7314227.0,-1,2019,4,Tuesday,3.0,0.0,Loss,238.0,-1.0

In [ ]:
df.isnull().sum()

published_date     0
open               0
high               0
low                0
close              0
per_change         0
traded_quantity    0
traded_amount      0
status             0
year               0
month              0
day_name           0
daily_range        0
price_change       0
status_label       0
prev_close         1
opening_gap        1
dtype: int64

*Since there is only one Null values that was created as there were no differences in price, we can simply fill it with 0*

In [ ]:
df.fillna(0)

,published_date,open,high,low,close,per_change,traded_quantity,traded_amount,status,year,month,day_name,daily_range,price_change,status_label,prev_close,opening_gap
0,2019-03-19,242.0,245.0,241.0,242.0,0.00,19638,4771501.0,0,2019,3,Tuesday,4.0,0.0,No Change,0.0,0.0
1,2019-03-21,242.0,245.0,238.0,240.0,-0.83,38970,9365431.0,-1,2019,3,Thursday,7.0,-2.0,Loss,242.0,0.0
2,2019-03-24,240.0,242.0,235.0,239.0,-0.42,41392,9872309.0,-1,2019,3,Sunday,7.0,-1.0,Loss,240.0,0.0
3,2019-03-25,238.0,241.0,236.0,240.0,0.42,35260,8436025.0,1,2019,3,Monday,5.0,2.0,Gain,239.0,-1.0
4,2019-03-26,237.0,241.0,237.0,241.0,0.42,31029,7417514.0,1,2019,3,Tuesday,4.0,4.0,Gain,240.0,-3.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1716,2026-10-01,190.0,193.0,189.5,191.0,1.00,79989,15315519.9,1,2026,10,Thursday,3.5,1.0,Gain,189.1,0.9
1717,2026-10-02,190.0,192.0,189.1,189.9,-0.58,65945,12548089.0,-1,2026,10,Friday,2.9,-0.1,Loss,191.0,-1.0
1718,2026-10-06,188.0,190.0,188.0,188.9,0.53,58933,11128338.7,1,2026,10,Tuesday,2.0,0.9,Gain,189.9,-1.9
1719,2026-10-07,188.1,190.0,188.1,189.0,0.05,53487,10109503.6,1,2026,10,Wednesday,1.9,0.9,Gain,188.9,-0.8
1720,2026-10-08,189.0,192.0,188.4,191.4,1.27,76446,14568143.2,1,2026,10,Thursday,3.6,2.4,Gain,189.0,0.0